image: php:7.2

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq
  # Install Xdebug
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  # Install php-intl
  - apt-get install -y libicu-dev g++
  - docker-php-ext-configure intl
  - docker-php-ext-install intl
  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  # Install all project dependencies
  - php composer.phar install --dev

test:app:
  script:
  - php vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --colors=never
