language: php
php: 7.2

git:
  depth: 3

install:
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

scripts:
  - composer lint
  - composer test
