language: php
php: 7.2

git:
  depth: 3

addons:
  sonarcloud:
    organization: "assoconnect"

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

scripts:
  - composer lint
  - composer test-coverage
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
