language: php
php:
  - 7.1
  - 7.2
install:
  - composer global require friendsofphp/php-cs-fixer
  - composer global require squizlabs/php_codesniffer
  - composer global require phpunit/phpunit

script:
  - phpunit
  - php-cs-fixer fix
  - phpcs
