services:

    assoconnect_doctrine_validator_bundle.validator:
        public: true
        alias: AssoConnect\DoctrineValidatorBundle\Validator\Constraints\EntityValidator

    AssoConnect\DoctrineValidatorBundle\Validator\Constraints\EntityValidator:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        tags:
            - validator.constraint_validator